sudo: required
language: cpp

compiler:  
    - gcc

before_install:
  - sudo apt-get update -q


install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6


before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: 
    - make

